#!/usr/bin/env bash
#
# CyberArk Account Provisioning Script for Linux
# ================================================
# Creates three local accounts for CyberArk PAM integration:
#   - ca_usr   : Standard user (static password)
#   - ca_adm   : Sudoer / Administrator equivalent (static password)
#   - ca_recon  : Reconcile account with password-reset rights for ca_usr & ca_adm (random password)
#
# Must be run as root or with sudo.
# Tested on RHEL 7/8/9, Ubuntu 18.04/20.04/22.04/24.04, Debian 10/11/12, Rocky/Alma 8/9.

set -euo pipefail

# ============================================================
# CONFIGURATION - edit static passwords here before deployment
# ============================================================
STATIC_PASSWORD_CA_USR="CyB3r@rk_Usr!2025"
STATIC_PASSWORD_CA_ADM="CyB3r@rk_Adm!2025"

RECON_PASSWORD_LENGTH=16
PASSWORD_FILENAME="ca_recon_password.txt"

# Detect the active non-root user who invoked sudo (for password file storage)
if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    ACTIVE_USER="${SUDO_USER}"
else
    # Fallback: find the first non-root user with a home directory
    ACTIVE_USER=$(awk -F: '$3 >= 1000 && $3 < 65534 && $7 !~ /nologin|false/ {print $1; exit}' /etc/passwd)
fi

if [[ -z "${ACTIVE_USER:-}" ]]; then
    echo "[ERROR] Could not determine active non-root user. Exiting."
    exit 1
fi

ACTIVE_USER_HOME=$(eval echo "~${ACTIVE_USER}")
PASSWORD_FILE_PATH="${ACTIVE_USER_HOME}/${PASSWORD_FILENAME}"

# ============================================================
# PRE-FLIGHT CHECKS
# ============================================================
if [[ "$(id -u)" -ne 0 ]]; then
    echo "[ERROR] This script must be run as root or with sudo."
    exit 1
fi

# ============================================================
# FUNCTIONS
# ============================================================

generate_random_password() {
    local length="${1:-16}"
    local password=""

    # Character pools
    local upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    local lower="abcdefghijklmnopqrstuvwxyz"
    local digits="0123456789"
    local symbols='!@#$%^&*()-_=+[]{}|;:,.<>?'
    local all="${upper}${lower}${digits}${symbols}"

    # Guarantee at least one from each pool
    password+="${upper:$((RANDOM % ${#upper})):1}"
    password+="${lower:$((RANDOM % ${#lower})):1}"
    password+="${digits:$((RANDOM % ${#digits})):1}"
    password+="${symbols:$((RANDOM % ${#symbols})):1}"

    # Fill remaining characters
    local remaining=$((length - 4))
    for ((i = 0; i < remaining; i++)); do
        # Use /dev/urandom for better randomness
        local idx
        idx=$(od -An -tu4 -N4 /dev/urandom | tr -d ' ')
        idx=$((idx % ${#all}))
        password+="${all:${idx}:1}"
    done

    # Shuffle the password (Fisher-Yates via shuf)
    echo "${password}" | fold -w1 | shuf | tr -d '\n'
}

create_user_account() {
    local username="$1"
    local password="$2"
    local description="$3"
    local shell="${4:-/bin/bash}"

    # Check if user already exists
    if id "${username}" &>/dev/null; then
        echo "[WARN] Account '${username}' already exists. Skipping creation."
        return 1
    fi

    # Create user with home directory
    useradd -m -s "${shell}" -c "${description}" "${username}"

    # Set password
    echo "${username}:${password}" | chpasswd

    # Verify creation using built-in getent
    if getent passwd "${username}" &>/dev/null; then
        echo "[OK] Account '${username}' created successfully."
        echo "     UID: $(id -u "${username}"), GID: $(id -g "${username}"), Home: $(eval echo "~${username}")"
        return 0
    else
        echo "[ERROR] Failed to create account '${username}'."
        return 1
    fi
}

configure_recon_delegation() {
    local recon_user="$1"
    shift
    local target_users=("$@")

    echo "[INFO] Configuring password-reset delegation for '${recon_user}'..."

    # Create a sudoers drop-in file that allows ca_recon to run passwd for target users ONLY
    local sudoers_file="/etc/sudoers.d/cyberark_recon"

    # Build the command list
    local passwd_cmds=""
    for target in "${target_users[@]}"; do
        if [[ -n "${passwd_cmds}" ]]; then
            passwd_cmds+=", "
        fi
        passwd_cmds+="/usr/bin/passwd ${target}"
    done

    # Write sudoers rule (strict: NOPASSWD only for specific passwd commands)
    cat > "${sudoers_file}" <<EOF
# CyberArk Reconcile Account - Password Reset Delegation
# Generated by linux_make_ca_account.sh
# Allows ${recon_user} to reset passwords for: ${target_users[*]}
# DO NOT EDIT MANUALLY - managed by CyberArk provisioning scripts

${recon_user} ALL=(root) NOPASSWD: ${passwd_cmds}
EOF

    chmod 0440 "${sudoers_file}"

    # Validate sudoers syntax
    if visudo -cf "${sudoers_file}" &>/dev/null; then
        echo "[OK] Sudoers delegation configured: ${sudoers_file}"
        echo "     ${recon_user} can reset passwords for: ${target_users[*]}"
    else
        echo "[ERROR] Sudoers syntax validation failed! Removing invalid file."
        rm -f "${sudoers_file}"
        return 1
    fi
}

# ============================================================
# MAIN
# ============================================================

echo ""
echo "============================================="
echo " CyberArk Account Provisioning - Linux"
echo "============================================="
echo ""
echo " Active user detected: ${ACTIVE_USER}"
echo " Password file path:   ${PASSWORD_FILE_PATH}"
echo ""

# --- Step 1: Generate random password for ca_recon ---
RECON_PASSWORD=$(generate_random_password "${RECON_PASSWORD_LENGTH}")

# --- Step 2: Ask user how to handle ca_recon password ---
echo "How would you like to handle the ca_recon password?"
echo "  [1] Save to file only   (${PASSWORD_FILE_PATH})"
echo "  [2] Display in terminal only"
echo "  [3] Save to file AND display in terminal"
echo ""

while true; do
    read -rp "Select option (1/2/3): " choice
    case "${choice}" in
        1|2|3) break ;;
        *) echo "Invalid selection. Please enter 1, 2, or 3." ;;
    esac
done

# --- Step 3: Create accounts ---
echo ""
echo "--- Creating accounts ---"

create_user_account "ca_usr" "${STATIC_PASSWORD_CA_USR}" "CyberArk PAM - Standard managed account"
create_user_account "ca_adm" "${STATIC_PASSWORD_CA_ADM}" "CyberArk PAM - Privileged managed account"
create_user_account "ca_recon" "${RECON_PASSWORD}" "CyberArk PAM - Reconcile account"

# --- Step 4: Assign privileges ---
echo ""
echo "--- Configuring privileges ---"

# ca_usr: standard user, no extra groups needed
echo "[OK] ca_usr -> standard user (no elevated privileges)"

# ca_adm: add to sudo/wheel group (Administrator equivalent)
if getent group sudo &>/dev/null; then
    usermod -aG sudo ca_adm
    echo "[OK] ca_adm -> 'sudo' group (Administrator)"
elif getent group wheel &>/dev/null; then
    usermod -aG wheel ca_adm
    echo "[OK] ca_adm -> 'wheel' group (Administrator)"
else
    echo "[WARN] Neither 'sudo' nor 'wheel' group found. Creating sudoers entry directly."
    echo "ca_adm ALL=(ALL:ALL) ALL" > /etc/sudoers.d/cyberark_ca_adm
    chmod 0440 /etc/sudoers.d/cyberark_ca_adm
    if visudo -cf /etc/sudoers.d/cyberark_ca_adm &>/dev/null; then
        echo "[OK] ca_adm -> direct sudoers entry created"
    else
        echo "[ERROR] Sudoers validation failed for ca_adm!"
        rm -f /etc/sudoers.d/cyberark_ca_adm
    fi
fi

# ca_recon: password-reset delegation only
configure_recon_delegation "ca_recon" "ca_usr" "ca_adm"

# --- Step 5: Lock down ca_recon (no interactive login shell, no SSH by default) ---
# ca_recon should only be used for password resets via CyberArk, not interactive sessions.
# We keep the shell for CyberArk CPM compatibility but restrict SSH if sshd_config exists.
if [[ -f /etc/ssh/sshd_config ]]; then
    if ! grep -q "^# CyberArk ca_recon restriction" /etc/ssh/sshd_config; then
        cat >> /etc/ssh/sshd_config <<'EOF'

# CyberArk ca_recon restriction - allow SSH for CPM reconciliation
# Remove or modify this block if ca_recon needs different SSH access
Match User ca_recon
    PasswordAuthentication yes
    AllowTcpForwarding no
    X11Forwarding no
    PermitTunnel no
    ForceCommand /bin/bash
EOF
        echo "[OK] SSH restrictions applied for ca_recon in sshd_config"
        echo "     (Restart sshd to apply: systemctl restart sshd)"
    fi
fi

# --- Step 6: Handle ca_recon password output ---
echo ""
echo "--- ca_recon password handling ---"

save_password_to_file() {
    cat > "${PASSWORD_FILE_PATH}" <<EOF
# CyberArk Reconcile Account Password
# Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')
# Host: $(hostname)
# WARNING: Store securely and delete after onboarding to CyberArk Vault.

Username: ca_recon
Password: ${RECON_PASSWORD}
EOF
    # Restrict permissions: owner (active user) read-only, no group/other access
    chown "${ACTIVE_USER}":"$(id -gn "${ACTIVE_USER}")" "${PASSWORD_FILE_PATH}"
    chmod 0400 "${PASSWORD_FILE_PATH}"
    echo "[OK] Password saved to: ${PASSWORD_FILE_PATH}"
    echo "     File permissions: 0400 (owner read-only), Owner: ${ACTIVE_USER}"
}

display_password_in_terminal() {
    echo ""
    echo "+---------------------------------------------+"
    echo "|  ca_recon Password (COPY NOW - shown once)  |"
    echo "+---------------------------------------------+"
    echo "|  ${RECON_PASSWORD}                           |"
    echo "+---------------------------------------------+"
    echo ""
}

case "${choice}" in
    1)
        save_password_to_file
        ;;
    2)
        display_password_in_terminal
        ;;
    3)
        save_password_to_file
        display_password_in_terminal
        ;;
esac

# --- Summary ---
echo ""
echo "============================================="
echo " PROVISIONING COMPLETE"
echo "============================================="
echo ""
echo " Account Summary:"

for acct in ca_usr ca_adm ca_recon; do
    if id "${acct}" &>/dev/null; then
        groups_list=$(groups "${acct}" 2>/dev/null | cut -d: -f2 | xargs)
        echo "   ${acct}  |  UID: $(id -u "${acct}")  |  Groups: ${groups_list}"
    else
        echo "   ${acct}  |  NOT FOUND (creation may have failed)"
    fi
done

echo ""
echo " Next Steps:"
echo "   1. Onboard ca_usr and ca_adm to CyberArk Vault with their static passwords."
echo "   2. Onboard ca_recon as the reconcile account in the platform configuration."
echo "   3. Delete the password file after onboarding (if option 1 or 3 was selected)."
echo "   4. Restart sshd if SSH restrictions were applied: systemctl restart sshd"
echo ""
